Actividad_enlace=[
    "Monitoreo de Señales",
    "Supervisión C5",
    "Supervisión del C2ORIENTE",
    "Supervisión del C2PONIENTE",
    "Supervisión del C2SUR",
    "Supervisión del C2NORTE",
    "Supervisión del C2CENTRO",
    "Supervisión del C2CEDA",
    "Supervisión del C2CHI",
    "Reparación de equipos de computo",
    "Habilitar Sala de tránsito ",
    "Soporte al 3er piso CG",
    "Atención  a Equipos Impresoras (Inventario, bajas)",
    "Monitoreo de Mesa y atención de tickets",
    "Mantenimiento de las WKS para DONACIONES",
    "Asignación de proyector",
    "Asignación de equipos Adminitrativos C2CHI",
    "Habilitar Auditorio",
    "Mantenimientos a estaciones de trabajo",
    "Marcas de Agua en C2CHI",
    "Reasignación de equipos del COE",
    "Habilitar sala pasteles",
    "Soporte a  equipos Video Wall_OI",
    "Atención de Oficios Instalación  software",
    "Actualización del WSUS",
    "Aplicación Marca de agua (Plantillas, Intalación)",
    "Atención a Alcaldias",
    "Implementación de Pantallas Audiovisuales",
    "Atención de Oficios Instalación de equipos",
    "órden de la Bodega de estaciones de trabajo",
    "Actualización de Inventario de las MDC",
    "Instalación Raspberry",
    "Creación de Imágenes Administrativas",
    "Creación de Imágenes Operativas",
    "Control de Imágenes C5, C2's",
    "Asignación de Proyector equipo OI",
    "Atención de tickets",
    "Puesta en marcha Señales",
    "Diagnostico de fallas",
    "Monitoreo Enlace Virreinal y Liverpool",
    "Encargado del Orden de la Bodega de Tóner/Componentes",
    "Reubicación de equipos Administrativos ",
    "Reubicación de equipos Operativos",
    "Reubicación de equipos Impresoras",
    "Inventario de componentes dañados",    
    "Inventario de stock de componentes",
    "Soporte a software",
    "Solicitud de liberación de puertos",
    "Solicitud de liberación puertas",
    "Apoyo a las mejoras de procesos",
    "Implementación de Imágenes C2CHI",
    "Diagnostico de fallas",
    "Apoyo a las actividades del Metro"
]
print(len(Actividad_enlace))
print(Actividad_enlace[52])
